### ISSUE TITLE
[1.12.2] Ticking entity crash.

### ISSUE THREAD

**Issue by SonicX8000** [DeflatedPickle/Heart-Drops#4]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 3
Forgelin-1.8.4
heartdrops-1.12.2-3.0.0.3
jei_1.12.2-4.15.0.291

Report:
https://pastebin.com/v1ASsuts

-----

I dunno if certain mobs are causing the crash to occur but I did catch this one from the Bat entity with only the above mods added... within 5 seconds of starting a new world.

Previous crashes were one from a RandomThings Soul but I had many mods added, tried again with only the above mods added and slayed a Zombie and got a crash... and then the Bat crashing the game within 5 seconds of starting a new world.

I dunno if any config changes are needed but these are the only options I've changed from the default.

Cap At Health: false
Drop Chance: CHANCE
Drop When: ALWAYS

...also the world that I just created is stuck in an endless crash loop, related to the same Bat entity. Although if I change the Drop When to HURT... I'm able to bypass the crash loop & log into the world.

**Comment by DeflatedPickle** [comment]
Do you have `Derive From Drops` as `true`? If yes, I think I know the problem.

**Comment by SonicX8000** [comment]
I think that was set to True, although I'll have to retest that.

**Comment by DeflatedPickle** [comment]
Alright, so I didn't account for something dying by anything but another entity, as when `Derive From Drops` is `true`, it casts the damage source to an `EntityLivingBase`.

**Comment by ArMoReDfUrY** [comment]
any update on this?

**Comment by DeflatedPickle** [comment]
@ArMoReDfUrY, I forgot about it, but I'll do it now.

**Comment by DeflatedPickle** [comment]
@Z-Tunic, that *should* fix it, though I haven't fixed it. I'll push a release to CurseForge in a bit.

**Comment by DeflatedPickle** [comment]
@ArMoReDfUrY, there's a 1.15 patch for this. Doesn't fix your issue, though. I'm not sure what causes that. It does seem like a Forge issue or some change between 1.14 and 1.15 I never noticed.

**Comment by ArMoReDfUrY** [comment]
they made some changes a week or so back. i'll post the note in the correct bug report now.

**Comment by SonicX8000** [comment]
Has the 1.12.2 version of the mod have the fix put in? I see it's been updated for 1.15 / 1.14 but the 1.12 version hasn't been updated by the looks of it.

**Comment by DeflatedPickle** [comment]
@Z-Tunic, please take a look at the linked pull requests, their state and the recent uploads on CurseForge. The only version I didn't update was 1.11, as it was just a joke.

I've left this issue open until you confirm it works, as I want to make sure it is for you.

**Comment by SonicX8000** [comment]
The latest version uploaded for the 1.12.2 version is 'heartdrops-1.12.2-3.0.0.3.jar' back on Apr 12, 2020... which has the ticking entity crash bug. I don't see any later versions uploaded besides for 1.14 / 1.15 versions of Minecraft.

I just did a gradlew build from the source and it's called 'heartdrops-1.12.2-3.0.0.4'. It did say 'build failed' but it still gave me a .jar file inside the 'build/libs' folder alongside the source jar.

Anyways... seems like it doesn't crash anymore... but again, I got a build failed so I dunno if there's any other side effects.

P.S.
How does one make it so Red Hearts appear by chance? Much like with Golden Hearts & Crystal Hearts? I have the config set at CHANCE with Drop Value at 2 with Drop Range at 1 & Drop When at ALWAYS and mobs still drop hearts 100% of the time.

There doesn't seem to be a chance value to change for Red Hearts that Gold & Crystal Hearts have unless I'm not understanding the options correctly.

**Comment by DeflatedPickle** [comment]
Ah. I had uploaded a version, but I took it down to decrement the version.

I know how to build my own mod.
The build failing notice is because of a Spotless check, it is noted in the crash report, please always read that if you're building a mod from source.

As for red hearts by chance, it's inverted in a 1-100 range. It's a chance for them ***NOT*** to drop. So, you're setting it to drop nearly all the time.

I know there ***IS*** a chance value. It was requested, I added it.
