### ISSUE TITLE
[1.15.2] Random Server Crash

### ISSUE THREAD

**Issue by mr-poyo** [DeflatedPickle/Heart-Drops#6]
Version: heartdrops-1.15.2-3.0.0.3.jar
Forge: 31.1.41

Randomly when I'm doing server tests in my survival world, I get this crash:

https://pastebin.com/BvT6bH3W

This particular crash happened when I saw a mutant zombie fighting a spider. He launched the spider into the air then I crashed. Hope this log helps! 

Thank you!

**Comment by DeflatedPickle** [comment]
Sorry, I didn't see this before. The [line the error refers to](https://github.com/DeflatedPickle/HeartDrops/blob/kotlin/src/main/kotlin/com/deflatedpickle/heartdrops/event/ForgeEventHandler.kt#L91) isn't even part of the function it refers to, so I don't actually know what went wrong. But following the stack trace, it's showing `at chumbanotz.mutantbeasts.entity.mutant.MutantZombieEntity$ThrowAttackGoal.func_75246_d(MutantZombieEntity.java:735)`. I don't know if this is doing anything that would affect HeartDrops, but it might be worth bringing up to the author of MutantBeasts.

**Comment by ArMoReDfUrY** [comment]
mutant beasts has a lot of issues working with other mods right now.
does not play nice with others...

**Comment by mr-poyo** [comment]
Thank you guys. At this point I concur this looks like it's tied to mutant beasts. Thanks for clearing that up!
